[package]
name = "never_type"
version = "0.1.0"
edition = "2024"
rust-version = "1.92.0"

[dependencies]
tokio = { version = "1.49.0", features = ["time", "rt", "rt-multi-thread", "macros", "sync"] }
